services:
  - type: web
    name: junbun
    env: python
    buildCommand: |
      poetry install --no-root
    startCommand: |
      export PATH="$HOME/.local/bin:$PATH"
      poetry run gunicorn junbun.wsgi:application --bind 0.0.0.0:$PORT
