# Generated by Django 5.1.4 on 2025-01-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='wordcloud_image',
            field=models.ImageField(blank=True, help_text='ワードクラウド画像', null=True, upload_to='wordcloud/'),
        ),
    ]
